# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{yalab-ruby-ods}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["yalab"]
  s.date = %q{2009-11-23}
  s.description = %q{}
  s.email = %q{rudeboyjet@gmail.com}
  s.files = [
    "VERSION",
     "lib/ods.rb",
     "test/cook.ods",
     "test/ods_test.rb"
  ]
  s.homepage = %q{http://github.com/yalab/ruby-ods}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{This is using OpenOffice SpreadSheet document file via ruby}
  s.test_files = [
    "test/ods_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

